version: '3'
services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    container_name: express-frontend
    environment:
      - API_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
